version: '3.9'

services:
  stemmarest:
    image: dhuniwien/stemmarest:latest

  stemweb_mysql:
    container_name: stemweb_mysql
    image: mariadb:10.4
    restart: always
    env_file:
      - stemweb/.env.prod

  stemweb_redis:
    container_name: stemweb_redis
    image: redis:alpine
    restart: always
    sysctls:
      # change this Linux Kernel Parameter (default is 128) within container because of this WARNING
      # "The TCP backlog setting of 511 cannot be enforced
      # because /proc/sys/net/core/somaxconn is set to the lower value of 128."
      net.core.somaxconn: 512     # maximal number of connections
    volumes:
      - ./stemweb/redis/redis.conf:/usr/local/etc/redis/redis.conf # version 6 from  https://redis.io/topics/config
    command:
      redis-server /usr/local/etc/redis/redis.conf

  stemweb:
    container_name: stemweb
    image: dhuniwien/stemweb_py37:latest
    restart: always
    env_file:
      - stemweb/.env.prod
    depends_on:
      - stemweb_mysql
      - stemweb_redis

  stemmarest-initializer:
    build: bin
    env_file:
      - .env.prod
    depends_on:
      - stemmarest
    volumes:
      - ./bin/init-data/:/init-data
    entrypoint: >
      /bin/bash -c "sleep 10 && /init-data/init_test_data.sh"

  stemmaweb:
    build: .
    env_file:
      - .env.prod

  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      - stemmaweb
    ports:
      - "8888:80"
