FROM alpine
LABEL vendor=DHUniWien

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    bash \
    gcc \
    make \
    libxml2 \
    libxml2-dev \
    zlib \
    zlib-dev \
    expat \
    graphviz \
    libssl1.1 \
    tzdata \
    wget \
    gmp \
    gmp-dev \
    expat \
    expat-dev \
    openssl \
    openssl-dev \
    openssh \
    libc-dev \
    perl \
    perl-dev \
    perl-ipc-system-simple

# download, compile and install Phylip Pars
WORKDIR /tmp
RUN wget http://evolution.gs.washington.edu/phylip/download/phylip-3.697.tar.gz \
 && tar -xzvf phylip-3.697.tar.gz
WORKDIR /tmp/phylip-3.697/src
RUN make -f Makefile.unx install \
 && cp ../exe/pars /usr/local/bin

# some of stemmaweb's dependencies fail tests or don't install cleanly from CPAN
RUN apk add --no-cache \
    perl-plack \
    perl-crypt-rijndael

RUN wget --no-check-certificate https://cpanmin.us -O cpanm && \
    perl cpanm App::cpanminus

# a few tests will fail in the build container
# in a not containerised environment the tests succeeed
RUN cpanm --notest IO::All Net::SSLeay

# install the other ones honestly, with tests
# First get the modules whose dependents don't record them accurately
# enough for cpanm to notice they are needed
RUN cpanm \
    Cookie::Baker \
    Devel::OverloadInfo \
    HTTP::Entity::Parser \
    HTTP::Headers::Fast \
    Module::Install::Catalyst \
    || (cat /root/.cpanm/work/*/build.log; exit 1)

# Then get the modules referenced directly in the Makefile.PL
WORKDIR /tmp
COPY Makefile.PL /tmp
RUN grep requires Makefile.PL | \
    cut -d ' ' -f 2 | \
    sed -e 's/;//' | \
    xargs cpanm && rm Makefile.PL
