FROM ubuntu:noble

# Make sure that we don't get any interactive prompts
ENV DEBIAN_FRONTEND noninteractive

# Install Python and aux packages
RUN apt-get update && apt-get install -y \
    python3.12 \
    pipx \
    python3-setuptools \
    python3-wheel \
    build-essential \
    locales

# Alias `python3` to `python` and `pip3` to `pip`
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1 

# Install Node.js
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    ca-certificates \
    lsb-release &&  \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&  \
    apt-get install -y nodejs

# Update npm (got installed in the previous layer with `nodejs`)
RUN npm install -g npm@10.9.2

# Install utilities
RUN apt-get update && apt-get install -y \
    make \
    jq \
    vim && \
    pipx ensurepath --global && \
    pipx install killport && \
    pipx install ipython

# Install Poetry
RUN pipx install poetry

# Install Poetry dependencies
COPY middleware/poetry.lock middleware/pyproject.toml ./
RUN poetry config virtualenvs.create false && \
    poetry install

WORKDIR /usr/src
