version: '3.9'

services:
  stemmarest:
    image: "dhuniwien/stemmarest:latest"

  stemmaweb:
    build: .
    env_file:
      - .env

  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      - stemmaweb
    ports:
      - "8080:80"
