version: '3.9'

services:
  stemmarest:
    image: "dhuniwien/stemmarest:latest"

  stemmarest-initializer:
    build: bin
    env_file:
      - .env.prod
    depends_on:
      - stemmarest
    volumes:
      - ./bin/init-data/:/init-data
    entrypoint: >
      /bin/bash -c "sleep 10 && /init-data/init_test_data.sh"

  stemmaweb:
    build: .
    env_file:
      - .env.prod

  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      - stemmaweb
    ports:
      - "8888:80"
