FROM ubuntu:noble

# Make sure that we don't get any interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install Python and aux packages
RUN apt-get update && apt-get install -y \
    python3.12 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    build-essential \
    locales

# Alias `python3` to `python` and `pip3` to `pip`
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# Install Node.js
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    ca-certificates \
    lsb-release &&  \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&  \
    apt-get install -y nodejs

# Update npm (got installed in the previous layer with `nodejs`)
RUN npm install -g npm@10.9.2

# Install utilities. Since it's a container we cheerfully install everything globally
RUN apt-get update && apt-get install -y \
    make \
    jq \
    vim && \
    pip config set global.break-system-packages true && \
    pip install killport ipython

# Install Poetry
RUN pip install poetry

# Install Poetry dependencies
COPY middleware/poetry.lock middleware/pyproject.toml ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

WORKDIR /usr/src
