FROM python:3.14-slim-bookworm

# Make sure that we don't get any interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages and Node.js 24
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    gnupg \
    ca-certificates \
    lsb-release \
    locales \
    make \
    jq \
    vim && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs

# Install utilities. Since it's a container we cheerfully install everything globally
RUN pip install killport ipython

# Install Poetry
RUN pip install poetry

# Install Poetry dependencies
COPY middleware/poetry.lock middleware/pyproject.toml ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

WORKDIR /usr/src
