version: '3.9'

services:
  stemmarest:
    image: "dhuniwien/stemmarest:latest"

  stemmarest-initializer:
    build: bin
    env_file:
      - .env.test
    depends_on:
      - stemmarest
    volumes:
      - ./bin/init-data/stemmarest/:/init-data
    entrypoint: >
      /bin/bash -c "./wait-for-it.sh --host=${STEMMAREST_HOST} --port=${STEMMAREST_PORT} -- /init-data/init_test_data.sh"

  stemweb:
    container_name: stemweb
    build: stemweb_mock
    ports:
      - "8000:8000"

  stemmaweb:
    container_name: stemmaweb
    build: .
    depends_on:
      - stemmarest
      - stemweb
    env_file:
      - .env.test
    volumes:
      - ./frontend/config/env.js.prod:/usr/src/app/stemmaweb_middleware/stemmaweb/src/js/env.js

  stemmaweb-e2e:
    container_name: stemmaweb-e2e
    build: frontend-e2e
    depends_on:
      - stemmaweb
      - stemmarest-initializer
    env_file:
      - .env.test
    volumes:
      - ./frontend-e2e/:/app
      - ./bin/init-data/stemmarest/:/app/cypress/.initdata4headless
    entrypoint: >
      /bin/bash -c "sleep 120 &&  # Waiting for other services to be ready
                    npm install -g npm@10.9.2 &&
                    npm install &&
                    npm run ${CY_NPM_COMMAND}"
