# version: '3.9'

services:
  shell:
    build: bin
    env_file:
      - .env.dev
    volumes:
      - .:/usr/src

  stemmarest:
    image: dhuniwien/stemmarest:latest
    ports:
      - "8080:8080"

  stemmarest-initializer:
    build: bin
    env_file:
      - .env.dev
    depends_on:
      - stemmarest
    volumes:
      - ./bin/init-data/stemmarest/:/init-data
    entrypoint: >
      /bin/bash -c "./wait-for-it.sh --host=${STEMMAREST_HOST} --port=${STEMMAREST_PORT} -- /init-data/init_test_data.sh"

  stemweb:
    container_name: stemweb
    build: stemweb_mock
    ports:
      - "8000:8000"

  stemmaweb:
    container_name: stemmaweb
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src
    env_file:
      - .env.dev
    entrypoint: >
      /bin/bash -c "make install-middleware && 
                    make install-frontend &&
                    tail -F just-forcing-the-container-to-keep-running"
    ports:
      - "5678:5678"

  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      - stemmaweb
    ports:
      - "8888:80"
