name: Build and push tagged

on:
  push:
    branches: [ master ]
    paths:
      - root
      - lib
      - Dockerfile
  workflow_dispatch:

jobs:
  # Push bootstrap image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push development image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: dhuniwien/stemmaweb:master
      - name: Build and push FCGI image
        id: docker_build_fcgi
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-fcgi
          push: true
          platforms: linux/amd64,linux/arm64
          tags: dhuniwien/stemmaweb:master-fcgi
  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Rancher
        run: |
          curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BEARER_TOKEN }}"
